// This file is auto-generated by @hey-api/openapi-ts

export type AddNewWordRequest = {
    word: string;
};

export type AddNewWordResponse = {
    item: Item;
    userWordId: string;
};

export type GeneralErrorResponse = {
    /**
     * エラーメッセージ（文字列）
     */
    detail: string;
};

export type GetUserWordListResponse = {
    wordlist: Array<Item>;
    userid: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Item = {
    word: string;
    meaning: string;
    exampleSentence: string;
    exampleSentenceTranslation: string;
};

export type SigninRequest = {
    username_or_email: string;
    password: string;
};

export type SigninResponse = {
    access_token: string;
    token_type: string;
};

export type SignupRequest = {
    username: string;
    email: string;
    full_name?: string | null;
    disabled?: boolean;
    password: string;
};

export type SignupResponse = {
    username: string;
    email: string;
    full_name?: string | null;
    disabled?: boolean;
    _id: string;
};

export type SuggestWordsResponse = {
    items: Array<Item>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type SigninData = {
    body: SigninRequest;
    path?: never;
    query?: never;
    url: '/user/signin';
};

export type SigninErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SigninError = SigninErrors[keyof SigninErrors];

export type SigninResponses = {
    /**
     * sign in user
     */
    201: SigninResponse;
};

export type SigninResponse2 = SigninResponses[keyof SigninResponses];

export type AuthSignupData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/user/signup';
};

export type AuthSignupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthSignupError = AuthSignupErrors[keyof AuthSignupErrors];

export type AuthSignupResponses = {
    /**
     * add new user
     */
    201: SignupResponse;
};

export type AuthSignupResponse = AuthSignupResponses[keyof AuthSignupResponses];

export type AuthSignoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/signout';
};

export type AuthSignoutResponses = {
    /**
     * sign out of the user account
     */
    200: unknown;
};

export type AddNewWordData = {
    body: AddNewWordRequest;
    path?: never;
    query?: never;
    url: '/word/add_new_word';
};

export type AddNewWordErrors = {
    /**
     * リクエスト不正
     */
    400: GeneralErrorResponse;
    /**
     * 認証失敗
     */
    401: GeneralErrorResponse;
    /**
     * 権限なし
     */
    403: GeneralErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * サーバー内部エラー
     */
    500: GeneralErrorResponse;
};

export type AddNewWordError = AddNewWordErrors[keyof AddNewWordErrors];

export type AddNewWordResponses = {
    /**
     * Successful Response
     */
    200: AddNewWordResponse;
};

export type AddNewWordResponse2 = AddNewWordResponses[keyof AddNewWordResponses];

export type GetUserWordListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/word/get_user_word_list';
};

export type GetUserWordListErrors = {
    /**
     * リクエスト不正
     */
    400: GeneralErrorResponse;
    /**
     * 認証失敗
     */
    401: GeneralErrorResponse;
    /**
     * 権限なし
     */
    403: GeneralErrorResponse;
    /**
     * サーバー内部エラー
     */
    500: GeneralErrorResponse;
};

export type GetUserWordListError = GetUserWordListErrors[keyof GetUserWordListErrors];

export type GetUserWordListResponses = {
    /**
     * Successful Response
     */
    200: GetUserWordListResponse;
};

export type GetUserWordListResponse2 = GetUserWordListResponses[keyof GetUserWordListResponses];

export type SuggestWordsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * prefix / exact-first query
         */
        q: string;
        limit?: number;
    };
    url: '/word/suggest_words';
};

export type SuggestWordsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SuggestWordsError = SuggestWordsErrors[keyof SuggestWordsErrors];

export type SuggestWordsResponses = {
    /**
     * Successful Response
     */
    200: SuggestWordsResponse;
};

export type SuggestWordsResponse2 = SuggestWordsResponses[keyof SuggestWordsResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};