version: "3.8"

services:
  fastapi:
    image: "fastapi:${TAG-latest}"
    links:
      - mongo
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 4000:${SERVICE_PORT}
    volumes:
      - ./app:/app:cached
    env_file:
      - ./.env
    environment:
      HOST: 0.0.0.0
      PORT: ${SERVICE_PORT}
      LOG_LEVEL: info
      LOGCONFIG: ./logging.conf
      WORKERS: 1
      APP_MODULE: main:app
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mongo
      DB_PORT: 27017
    tty: true
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: app
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo_dev:/data/db
    tty: true
    restart: unless-stopped

  mongoexpress:
    image: mongo-express:0.54
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      VCAP_APP_HOST: 0.0.0.0
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
    restart: unless-stopped
