services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: "fastapi:latest"
    ports:
      - 4000:${SERVICE_PORT}
    volumes:
      - ./app:/app:cached
    env_file:
      - ./.env
    environment:
      HOST: 0.0.0.0
      PORT: ${SERVICE_PORT}
      LOG_LEVEL: info
      LOGCONFIG: ./logging.conf
      WORKERS: 1
      APP_MODULE: main:app
      DB_USERNAME: admin 
      DB_PASSWORD: pass 
      DB_HOST: mongo
      DB_PORT: 27017
    tty: true
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: app
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo_dev:/data/db
    tty: true
    restart: unless-stopped

  mongoexpress:
    image: mongo-express:latest
    links:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      VCAP_APP_HOST: 0.0.0.0
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    restart: unless-stopped
