# cookie settings
ACCESS_TOKEN_EXPIRE_MINUTES = 30

# word suggest 
MAX_NUM_WORD_SUGGEST = 10
MAX_NUM_WORD_SUGGEST_CANDIDATE = 100

# validation 
USERNAME_MIN_LEN = 3 
USERNAME_MAX_LEN = 25

PASSWORD_MIN_LEN = 8
PASSWORD_MAX_LEN = 25
PASSWORD_REGEX_PATTERN = r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d@$#!%*?&]{8,}$"

SPELLING_MIN_LEN = 1
SPELLING_MAX_LEN = 45

MEANING_MAX_LEN = 45

EXAMPLE_MAX_LEN = 150

EXAMPLE_TRANSLATION_MAX_LEN = 150
